// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-lessons.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_lessons_default = defineTool({
  name: "list_lessons",
  title: "List saved lessons",
  description: "List the signed-in user's saved differentiated lessons, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max number of lessons to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("generated_lessons").select("id, lesson_title, group_ids, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lessons: data }
    };
  }
});

// src/lib/mcp/tools/get-lesson.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_lesson_default = defineTool2({
  name: "get_lesson",
  title: "Get lesson",
  description: "Fetch a single saved lesson (teacher guide, student handouts, differentiation options) by ID.",
  inputSchema: {
    lessonId: z2.string().uuid().describe("The lesson's UUID (from list_lessons).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lessonId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("generated_lessons").select("*").eq("id", lessonId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Lesson not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lesson: data }
    };
  }
});

// src/lib/mcp/tools/list-student-groups.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_student_groups_default = defineTool3({
  name: "list_student_groups",
  title: "List student groups",
  description: "List the signed-in user's student groups with reading level, home language, ELL and IEP/504 status.",
  inputSchema: {
    folderId: z3.string().uuid().optional().describe("Optional class folder ID to scope results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ folderId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let query = supabase.from("student_groups").select("id, group_name, num_students, reading_level_label, home_language, ell_status, iep_504_status, accommodations, folder_id, updated_at").order("updated_at", { ascending: false });
    if (folderId) query = query.eq("folder_id", folderId);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { groups: data }
    };
  }
});

// src/lib/mcp/tools/list-rubrics.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.87.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_rubrics_default = defineTool4({
  name: "list_rubrics",
  title: "List saved rubrics",
  description: "List the signed-in user's saved rubrics, most recent first.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Max number of rubrics to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("generated_rubrics").select("id, rubric_name, rubric_content, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { rubrics: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vdjiqdvrpeavnhyiovvn";
var mcp_default = defineMcp({
  name: "authentic-learning-studio-mcp",
  title: "Authentic Learning Studio",
  version: "0.1.0",
  instructions: "Tools for the Authentic Learning Studio. Use list_lessons and get_lesson to read the signed-in teacher's differentiated lessons, list_student_groups to inspect their student groups, and list_rubrics for saved rubrics.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_lessons_default, get_lesson_default, list_student_groups_default, list_rubrics_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
